#!/usr/bin/env bash

BASE_PATH=ENTER THE PATH TO YOUR BASE DOWNLOAD DIR HERE
BASE_URL=ENTER THE BASE URL OF YOUR TORPEDO INSTANCE HERE
TORPEDO_BIN=ENTER THE PATH TO YOUR TORPEDO INSTALLATION HERE # required to launche the full-fledged command

$TORPEDO_BIN/create_download.sh $BASE_URL $BASE_PATH "$@"
