name: Torpedo Docker Build

on:
  push:

jobs:
  
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: foo
        run: ls -la /usr/share/dotnet/host/fxr
      -
        name: Customizable Docker Buildx Build
        uses: ilteoood/docker_buildx@1.0.5
        with:
          tag: latest
          imageName: b0wter/torpedo
          context: src/webapi/
          dockerFile: src/webapi/Dockerfile.arm32
          platform: linux/arm/v7
          
